config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # get 'password_resets/new'
  # get 'password_resets/create'
  # get 'password_resets/edit'
  # get 'password_resets/update'
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'static_pages#top'
  # root 'restaurants#index'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resources :restaurants, only: %i[index show] do
    collection do
      get :search
      get :bookmarks
    end
    member do
      post 'update_tag'
    end
  end
  post 'select_restaurants', to: 'restaurants#random_select', as: 'select_restaurants'
  post 'get_location', to: 'locations#get_location'
  resources :bookmarks, only: %i[create destroy]
  get "/pages/*id" => 'pages#show', as: :page, format: false
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/views/shared/_before_login_header.html.erb
<div class="navbar bg-base-100 bg-cyan-800">
  <div class="navbar-start">
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost lg:hidden">
        <i class="fa-solid fa-bars fa-xl" style="color: #fcfcfc;"></i>
      </label>
      <ul tabindex="0" class="menu menu-lg dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <li><%= link_to t('defaults.search'), search_restaurants_path %></li>
        <li><%= link_to t('restaurants.bookmarks.title'), bookmarks_restaurants_path %></li>
      </ul>
    </div>
    <%= link_to 'HASHIGO', root_path,class:"btn btn-ghost normal-case text-xl text-neutral-50" %>
  </div>
    <div class="navbar-center hidden lg:flex text-neutral-50">
    <ul class="menu menu-horizontal px-1">
      <li><%= link_to t('defaults.search'), search_restaurants_path %></li>
      <li><%= link_to t('restaurants.bookmarks.title'), bookmarks_restaurants_path %></li>
    </ul>
  </div>
<div class="navbar-end flex">
    <%= link_to t('users.new.title'), new_user_path, class: 'bg-transparent hover:bg-blue-500 text-neutral-50 font-semibold hover:text-neutral-50 py-4 px-4 border border-neutral-50 hover:border-transparent rounded-full mr-4' %>
    <%= link_to t('user_sessions.new.title'), login_path, class: 'btn rounded-full' %>
</div>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-base-200 text-base-content bg-cyan-800">
  <div class="grid grid-flow-col gap-4">
    <%= link_to t('defaults.terms_of_use'), page_path('terms'), class: "link link-hover text-neutral-50" %>
    <%= link_to t('defaults.privacy_policy'), page_path('privacy'), class: "link link-hover text-neutral-50" %>
    <%= link_to t('defaults.contact'), 'https://twitter.com/okada84108983', class: "link link-hover text-neutral-50"%>
  </div>
  <div class="text-neutral-50">
    <p>Photo by <a href="https://unsplash.com/@fwed?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Fred Moon</a> on <a href="https://unsplash.com/photos/0yqa0rMCsYk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  </p>
    <p>Copyright © 2023 - All right reserved by HASHIGO</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100 bg-cyan-800">
  <div class="navbar-start">
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost lg:hidden">
        <i class="fa-solid fa-bars fa-xl" style="color: #fcfcfc;"></i>
      </label>
      <ul tabindex="0" class="menu menu-lg dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <li><%= link_to t('defaults.search'), search_restaurants_path %></li>
        <li><%= link_to t('defaults.bookmarks'), bookmarks_restaurants_path %></li>
      </ul>
    </div>
    <%= link_to 'HASHIGO', root_path,class:"btn btn-ghost normal-case text-xl text-neutral-50" %>
  </div>
    <div class="navbar-center hidden lg:flex text-neutral-50">
    <ul class="menu menu-horizontal px-1">
      <li><%= link_to t('defaults.search'), search_restaurants_path %></li>
      <li><%= link_to t('restaurants.bookmarks.title'), bookmarks_restaurants_path %></li>
    </ul>
  </div>
  <div class="navbar-end">
    <%= link_to t('defaults.logout'), logout_path, data: { turbo_method: :delete }, class:'btn rounded-full'%>
  </div>
</div>