config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # get 'password_resets/new'
  # get 'password_resets/create'
  # get 'password_resets/edit'
  # get 'password_resets/update'
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'static_pages#top'
  # root 'restaurants#index'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resources :restaurants, only: %i[index show] do
    collection do
      get :search
      get :bookmarks
    end
    member do
      post 'update_tag'
    end
  end
  post 'select_restaurants', to: 'restaurants#random_select', as: 'select_restaurants'
  post 'get_location', to: 'locations#get_location'
  resources :bookmarks, only: %i[create destroy]
  get "/pages/*id" => 'pages#show', as: :page, format: false
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  acts_as_taggable_on :tags
  has_many :bookmarks, dependent: :destroy
  validates :place_id, presence: true
  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  def self.find_or_create_from_api_data(data)
    restaurant = find_or_initialize_by(place_id: data['place_id'])
    return restaurant if restaurant.persisted?

    details = fetch_place_details(data['place_id'])

    if details['photos'].present?
      photo = details['photos'].first
      photo_url = "https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=#{photo['photo_reference']}&key=#{ENV.fetch('GOOGLE_API_KEY', nil)}"
      html_attributions = photo['html_attributions'].first
    end
    restaurant.attributes = {
        place_id: details['place_id'],
        name: details['name'],
        latitude: details['geometry']['location']['lat'],
        longitude: details['geometry']['location']['lng'],
        address: details['formatted_address'] || details['vicinity'],
        rating: details['rating'],
        phone_number: details['formatted_phone_number'],
        categories: details['types'],
        price_level: details['price_level'],
        image_url: photo_url,
        html_attributions: html_attributions,
        url: details['url'],
        opening_hours: details['opening_hours'] ? details['opening_hours']["weekday_text"].join(", ") : "N/A",
        total_ratings: details['user_ratings_total'] || 0,
        editorial_summary: details['editorial_summary'] ? details['editorial_summary']['overview'] : nil ,
        serves_beer: details['serves_beer'],
        serves_wine: details['serves_wine']
      }
    restaurant.save
    restaurant
  end
  
  def self.fetch_place_details(place_id)
    base_url = "https://maps.googleapis.com/maps/api/place/details/json"
    parameters = {
      place_id: place_id,
      fields: 'place_id,name,geometry,formatted_phone_number,vicinity,rating,types,price_level,photos,url,opening_hours,user_ratings_total,editorial_summary,serves_beer,serves_wine',
      key: ENV.fetch('GOOGLE_API_KEY', nil),
      language: 'ja'
    }
    response = Net::HTTP.get(URI("#{base_url}?#{parameters.to_query}"))
    JSON.parse(response)['result']
  end

  def bookmark_count
    bookmarks.count
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'

  skip_before_action :require_login, only: %i[index show search address_search]
  before_action :set_restaurant, only: %i[update_tag]

  def index
  end

  def show
    @restaurant = Restaurant.includes(:tags).find(params[:id]).decorate
  end

  def search
    if params[:address].present?
      restaurants_array = RestaurantDecorator.decorate_collection(fetch_restaurants)
      if restaurants_array.length == 0
        flash.now[:notice] = t('.not_found')
      end
      @restaurants = Kaminari.paginate_array(restaurants_array).page(params[:page])
    end
  end

  def bookmarks
    bookmark_restaurants = current_user.bookmark_restaurants.order(created_at: :desc).page(params[:page])
    @bookmark_restaurants = bookmark_restaurants.decorate
    @paginated_bookmarks = bookmark_restaurants
  end

  def update_tag
    @restaurant.tag_list = params[:restaurant][:tag_list]
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      flash[:error] = t('.fail')
      redirect_to @restaurant
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def search_params
    params.permit(:radius, :place_type, :rating, :latitude, :longitude, :address, :total_ratings, :open_now)
  end

  def find_or_create_restaurant(place_data)
    Restaurant.find_or_create_from_api_data(place_data)
  end

  def fetch_restaurants
    location = if params[:latitude] && params[:longitude].present?
                 { latitude: params[:latitude], longitude: params[:longitude] }
              elsif params[:address]
                 geo_result = Geocoder.search(params[:address]).first
                 unless geo_result&.latitude && geo_result&.longitude
                   flash[:error] = t('.fail')
                   return []
                 end
                 { latitude: geo_result.latitude, longitude: geo_result.longitude }
               end
  
    if location && location[:latitude] && location[:longitude]
      options = {}
      options[:opennow] = true if params[:open_now] == 'true'
      fetch_places_from_api("#{location[:latitude]},#{location[:longitude]}", options)
    else
      []
    end
  end

  def fetch_places_from_api(location, options = {})
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
    parameters = {
      location: location,
      radius: search_params[:radius] || 50,
      type: search_params[:place_type],
      key: ENV['GOOGLE_API_KEY'],
      language: 'ja'
    }.merge(options)

    url = base_url + parameters.to_query
    response = Net::HTTP.get(URI(url))
    results = JSON.parse(response)["results"]

    restaurants = results.map { |place_data| find_or_create_restaurant(place_data) }
    if search_params[:rating].present?
      restaurants.select! { |restaurant| restaurant.rating && restaurant.rating >= search_params[:rating].to_f }
    end
    if search_params[:total_ratings].present?
      restaurants.select! { |restaurant| restaurant.total_ratings && restaurant.total_ratings >= search_params[:total_ratings].to_i }
    end
    restaurants.sort_by! { |restaurant| -restaurant.rating.to_f }
    restaurants
  end
end

app/views/restaurants/_bookmark.html.erb
<%= link_to bookmarks_path(restaurant_id: restaurant.id), id: "js-bookmark-button-for-restaurant-#{restaurant.id}", class:"float-right", data: { turbo_method: :post } do %>
  <i class="fa-regular fa-bookmark fa-lg"></i>
<% end %>

app/views/restaurants/_bookmark_button.html.erb
<% if current_user&.bookmark?(restaurant) %>
  <%= render 'unbookmark', { restaurant: restaurant } %>
<% else %>
  <%= render 'bookmark', { restaurant: restaurant } %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div class="flex flex-wrap justify-between mb-4 justify-center" data-restaurant-container >
  <div class="w-full p-4">
  <div class="card flex flex-row border rounded-lg overflow-hidden shadow-lg" data-total_ratings="<%= restaurant.total_ratings %>" data-bookmarks="<%= restaurant.bookmark_count %>">
      <div class="form-control">
        <label class="label cursor-pointer">
          <input type="checkbox" class="hidden restaurant-checkbox checkbox checkbox-primary" data-restaurant-id="<%= restaurant.id %>">
        </label>
      </div>
      <div class="w-1/4">
        <%= image_tag (restaurant.image_url || 'default_image.png'), alt: restaurant.name,class: 'h-full w-full object-cover' %>
        <%= simple_format("Source of photo: #{restaurant.html_attributions}", class: "text-xs text-center mt-2") if restaurant.html_attributions.present? %>
      </div>
      <div class="w-3/4 p-4">
        <h2 class="card-title text-lg font-bold mb-2"><%= restaurant.name %></h2>
        <p><%= t('activerecord.attributes.restaurants.address')%>：<%= restaurant.address %></p>
        <p><%= t('activerecord.attributes.restaurants.phone_number')%>：<%= restaurant.phone_number %></p>
        <p><%= t('activerecord.attributes.restaurants.rating')%>：<%= restaurant.rating %></p>
        <p><%= t('activerecord.attributes.restaurants.total_ratings')%>：<%= restaurant.total_ratings %></p>
        <p><%= t('activerecord.attributes.restaurants.price_level')%>：<%= restaurant.price_level_str %></p>
        <p><%= t('restaurants.search.bookmark_count')%>：<%= restaurant.bookmark_count %></p>
        <div class="mt-4">
          <%= link_to (t 'restaurants.search.to_show_page'), restaurant_path(restaurant), class: "btn btn-secondary font-bold" %>
        </div>
      </div>
      <div class="absolute top-2 right-2">
        <%= render 'bookmark_button', restaurant: restaurant %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/_search_results.html.erb
<% if restaurants.present? %>
<div class="flex justify-between items-center mb-6">
  <p class="text-xl font-bold"><%= t 'restaurants.search.result' %></p>
  <div>
    <label for="sort-options" class="mr-2"><%= t 'restaurants.search.sorting' %>:</label>
    <select id="sort-options" class="input input-bordered">
      <option value="default"><%= t 'restaurants.search.default_sort' %></option>
      <option value="total_ratings"><%= t 'restaurants.search.total_ratings_disc' %></option>
      <option value="bookmarks"><%= t 'restaurants.search.bookmark_disc' %></option>
    </select>
  </div>
</div>
<div class="container mx-auto", id="restaurant-list">
  <%= render restaurants %>
</div>
<div class="mt-4 mb-6 text-center">
  <%= paginate restaurants %>
</div>
<div class="mt-4 mb-6 text-center">
  <button id="select-candidate-button" class="btn btn-secondary"><%= t 'restaurants.search.start_select' %></button>
  <button id="random-button" class="btn btn-secondary mb-2 hidden"><%= t 'restaurants.search.exec_random_select' %></button>
  <div class="mb-6 hidden" id="check-all-container">
    <%= check_box_tag 'check_all', '1', false, id: 'check-all' %>
    <%= label_tag 'check_all', '全てのお店を選択' %>
  </div>
  <p id="instruction" class="hidden"><%= t 'restaurants.search.instruction_for_select' %></p>
</div>
<% end %>

app/views/restaurants/_tags_section.html.erb
<div id="tag-section">
  <% restaurant.tags.each do |tag| %>
    <div class="badge badge-info bg-teal-300 font-bold gap-2">
      <%= tag.name %>
    </div>
  <% end %>

  <button id="edit-button" class="btn btn-secondary btn-xs">
    <%= restaurant.tags.any? ?  (t 'restaurants.show.edit') : (t 'restaurants.show.add_tag')  %>
  </button>
</div>

<div id="tag-form" style="display: none;">
  <%= form_with model: restaurant, url: update_tag_restaurant_path(restaurant), method: :post  do |f| %>
    <%= f.text_field :tag_list, value: restaurant.tag_list.join(", "), placeholder: ",カンマで区切って入力", class: "input input-bordered input-sm w-full max-w-xs" %>
    <%= f.submit restaurant.tag_list.length > 0 ? (t 'restaurants.show.update') : (t 'restaurants.show.add'), class: "btn btn-secondary btn-xs text-sky-800" %>
  <% end %>
</div>

<script>
document.addEventListener('turbo:load', function() {
  const editButton = document.getElementById("edit-button");
  const tagSection = document.getElementById("tag-section");
  const tagForm = document.getElementById("tag-form");
  if (tagForm) {
    const form = tagForm.querySelector('form');

    editButton.addEventListener("click", function() {
      tagSection.style.display = "none";
      tagForm.style.display = "block";
    });

    if (form) {
      form.addEventListener("submit", function(event) {
        tagForm.style.display = "none";
        tagSection.style.display = "block";
      });
    }
  }
});
</script>

app/views/restaurants/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(restaurant_id: restaurant.id)), id: "js-bookmark-button-for-restaurant-#{restaurant.id}", class:"float-right", data: { "turbo-method": :delete } do %>
  <i class="fa-solid fa-bookmark fa-lg" style="color: #14b8a6;"></i>
<% end %>

app/views/restaurants/bookmarks.html.erb
<div class="flex-grow flex justify-center">
  <div class="container mx-auto px-4 py-4 md:w-2/3 lg:w-1/2">
    <h1 class="text-2xl font-bold mt-8 mb-8 text-center"><%= t '.title' %></h1>

    <% if @bookmark_restaurants.present? %>
        <%= render @bookmark_restaurants %>
      <div class="mt-4 mb-6 text-center">
        <%= paginate @paginated_bookmarks %>
      </div>
    <% else %>
      <p><%= t'.no_result' %></p>
    <% end %>
  </div>
</div>

app/views/restaurants/search.html.erb
<div class="flex-grow flex items-center justify-center">
  <div class="container px-2 py-4">
    <div class="container px-8 py-8 md:rounded-md shadow-md mx-auto md:w-1/2 lg:w-1/3" >
      <div class="tabs flex justify-center">
        <button class="tab tab-bordered text-lg md:text-xl font-bold tab-active" data-target="search-form">現在地から検索</button>
        <button class="tab tab-bordered text-lg md:text-xl font-bold" data-target="address-search-form">入力住所から検索</button>
      </div>

      <div id="search-form" class="tab-content">
        <%= form_with url: search_restaurants_path, method: :get, local: true, id: 'address-form' do |f| %>
        <div class="mb-6 mt-6">
          <button type="button" id="get-location" class="btn"><%= t '.get_location' %></button>
        </div>
        <div class="mb-6">
          <%= f.label :address, (t '.address' )  %>
          <%= f.text_field :address, id: 'address', value: params[:address], class:"input input-bordered w-full max-w-sm" %>
          <%= f.hidden_field :latitude, id: 'latitude' %>
          <%= f.hidden_field :longitude, id: 'longitude' %>
        </div>
        <div class="mb-6">
          <%= f.label :radius,(t '.radius' ) %>
          <%= f.number_field :radius, value: params[:radius]|| 300, min: 50, max:5000, step: 50, class:"input input-bordered"  %>
        </div>
        <div class="divider font-bold">お店のタイプ</div>
        <div class="mb-6 px-4 flex justify-center">
          <div>
            <%= f.radio_button :place_type,'restaurant',checked:"checked", class: "radio radio-secondary" %>
            <%= f.label :place_type, (t '.restaurant' ) , class: "mr-8" %>
            <%= f.radio_button :place_type, 'bar', class: "radio radio-secondary"  %>
            <%= f.label :place_type, (t '.bar' ) %>
          </div>
        </div>
        <div class="divider font-bold">その他の絞り込み</div>
        <div class="mb-6">
          <%= f.label :rating, (t '.rating' )%>
          <%= f.select :rating, [["選択しない", nil], ["1以上", 1], ["2以上", 2], ["3以上", 3], ["4以上", 4], ["5", 5]], selected: params[:rating], include_blank: false, class:"select select-bordered" %>
        </div>
        <div class="mb-6">
          <%= f.check_box :total_ratings, { checked: true, class:"checkbox checkbox-secondary"},30, 0 %>
          <%= f.label :total_ratings, 'クチコミ数が30件以上のお店のみ表示する' %>
        </div>
        <div class="mb-6">
          <%= f.check_box :open_now, { checked: true, class:"checkbox checkbox-secondary"},true, false %>
          <%= f.label :open_now, '営業中のお店のみを表示する' %>
        </div>
        <div class="mb-6 flex justify-center">
          <%= f.submit (t '.submit' ), id: 'search-address',class:'btn btn-wide flex justify-center' %>
        </div>
        <% end %>
      </div>

      <div id="address-search-form" class="tab-content" style="display: none;">
      <%= form_with url: search_restaurants_path, method: :get, local: true, id: 'address-form' do |f| %>
        <div class="mb-6 mt-6">
          <%= f.label :address, (t '.address' ) %>
          <%= f.text_field :address, id: 'address', value: params[:address], class:"input input-bordered  w-full max-w-sm" %>
          <%= f.hidden_field :latitude, id: 'latitude' %>
          <%= f.hidden_field :longitude, id: 'longitude' %>
        </div>
        <div class="mb-6">
          <%= f.label :radius,(t '.radius' ) %>
          <%= f.number_field :radius, value: params[:radius]|| 300, min: 50, max:5000, step: 50, class:"input input-bordered"  %>
        </div>
        <div class="divider font-bold">お店のタイプ</div>
        <div class="mb-6 px-4 flex justify-center">
          <div>
            <%= f.radio_button :place_type,'restaurant',checked:"checked", class: "radio radio-secondary" %>
            <%= f.label :place_type, (t '.restaurant' ) , class: "mr-8" %>
            <%= f.radio_button :place_type, 'bar', class: "radio radio-secondary"  %>
            <%= f.label :place_type, (t '.bar' ) %>
          </div>
        </div>
        <div class="divider font-bold">その他の絞り込み</div>
        <div class="mb-6">
          <%= f.label :rating, (t '.rating' )%>
          <%= f.select :rating, [["選択しない", nil], ["1以上", 1], ["2以上", 2], ["3以上", 3], ["4以上", 4], ["5", 5]], selected: params[:rating], include_blank: false %>
        </div>
        <div class="mb-6">
          <%= f.check_box :total_ratings, { checked: true, class:"checkbox checkbox-secondary"},30, 0 %>
          <%= f.label :total_ratings, 'クチコミ数が30件以上のお店のみ表示する' %>
        </div>
        <div class="mb-6">
          <%= f.check_box :open_now, { checked: true, class:"checkbox checkbox-secondary"},true, false %>
          <%= f.label :open_now, '営業中のお店のみを表示する' %>
        </div>
        <div class="mb-6 flex justify-center">
          <%= f.submit (t '.submit' ), id: 'search-address',class:'btn btn-wide' %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="container mt-4 px-2 py-6 mx-auto md:w-2/3" >
      <%= render 'search_results', restaurants: @restaurants  %>
    </div>
  </div>
</div>

<script>
// タブの切り替えに関する処理
document.addEventListener('turbo:load', function() {
  const tabs = document.querySelectorAll('.tab');
  tabs.forEach(tab => {
    tab.addEventListener('click', function() {
      const target = this.getAttribute('data-target');
      document.querySelectorAll('.tab-content').forEach(content => {
        content.style.display = 'none';
      });
      document.getElementById(target).style.display = 'block';
      tabs.forEach(t => t.classList.remove('tab-active'));
      this.classList.add('tab-active');
    });
  });
});

// 現在地の取得、表示に関する処理
document.addEventListener('turbo:load', function() {
  const getLocationButton = document.getElementById('get-location');
  const searchButton = document.getElementById('search-address');

  if (getLocationButton) {
    getLocationButton.addEventListener('click', function() {
      if (!navigator.geolocation) {
        alert('Geolocation is not supported by your browser');
        return;
      }

      searchButton.disabled = true; // 住所が取得できるまでボタンを無効化する

      function success(position) {
        const latitude  = position.coords.latitude;
        const longitude = position.coords.longitude;

        // サーバーに緯度と経度を送信
        fetch('/get_location', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector("meta[name='csrf-token']").getAttribute("content")
          },
          body: JSON.stringify({latitude: latitude, longitude: longitude}),
        })
        .then(response => response.json())
        .then(data => {
          // レスポンスから住所を取得し、フォームにセット
          const addressInput = document.querySelector('input[name="address"]');
          addressInput.value = data.address;

          // hidden fieldに緯度と経度をセット
          document.getElementById('latitude').value = latitude;
          document.getElementById('longitude').value = longitude;

          searchButton.disabled = false; // ボタンを有効化
        });
      }

      function error() {
        alert('Unable to retrieve your location');
      }

      navigator.geolocation.getCurrentPosition(success, error);
    });
  }
});
</script>

app/views/restaurants/show.html.erb
<div class="bg-cyan-800">
  <div class="container mx-auto px-12 md:w-4/5 lg:w-1/2 mt-4 py-6 bg-white md:rounded-md md:drop-shadow-md">
    <div class="text-2xl font-bold mt-4 mb-4 flex items-center justify-between">
      <h1><%= @restaurant.name %></h1>
      <%= link_to(image_tag('LINE_Brand_icon.png', width: 40, height: 40), "https://line.me/R/share?text=https://hashigo.fly.dev/restaurants/#{@restaurant.id}") %>
    </div>
    <div>
      <%= @restaurant.editorial_summary %>
    </div>

    <div class="mb-4 ">
      <div id="map" class="w-full h-72 md:h-96 lg:w-full lg:h-96"></div>
    </div>

    <li><strong><%= t('activerecord.attributes.restaurants.address')%>：</strong> <%= @restaurant.address %>
    <li><strong><%= t('activerecord.attributes.restaurants.phone_number')%>：</strong> <%= @restaurant.phone_number %>
    <li><strong><%= t('activerecord.attributes.restaurants.price_level')%>：</strong> <%= @restaurant.price_level_str %>
    <li><strong><%= t('activerecord.attributes.restaurants.rating')%>：</strong> <%= @restaurant.rating %>
    <li><strong><%= t('activerecord.attributes.restaurants.total_ratings')%>：</strong> <%= @restaurant.total_ratings %>
    <li><strong><%= t('.bookmark_count')%>：</strong> <%= @restaurant.bookmark_count %>
    <li><strong><%= t('activerecord.attributes.tags.name')%>：</strong></p>
    <%= render partial: 'tags_section', locals: { restaurant: @restaurant } %>
    <li><strong>URL:</strong> <%= link_to @restaurant.url, @restaurant.url, target: "_blank" %></p>
    <% if @restaurant.opening_hours && @restaurant.opening_hours != "N/A" %>
      <li><strong><%= t('activerecord.attributes.restaurants.opening_hours') %>:</strong></li>
      <div class="px-4">
        <%= simple_format(@restaurant.opening_hours.gsub(",", "\n")) %>
      </div>
    <% end %>
    <div class="py-4">
      <ul class="list-none p-0 flex">
        <% if @restaurant.serves_beer %>
          <li class="mr-5 flex items-center">
            <%= image_tag 'beer.png', class: 'object-scale-down w-6 h-12 mr-2' %>ビール提供あり
          </li>
        <% end %>
        <% if @restaurant.serves_wine %>
          <li class="flex items-center">
            <%= image_tag 'wine.png', class: 'object-scale-down w-6 h-12 mr-2' %>ワイン提供あり
          </li>
        <% end %>
      </ul>
    </div>
      <% if @restaurant.image_url %>
      <%= image_tag (@restaurant.image_url), alt: @restaurant.name %>
      <%= simple_format("Photo by: #{@restaurant.html_attributions}") %>
    <% end %>
  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>
<script>

function initMap() {
  var restaurantLocation = {lat: <%= @restaurant.latitude %>, lng: <%= @restaurant.longitude %>};
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 15,
    center: restaurantLocation
  });
  var marker = new google.maps.Marker({
    position: restaurantLocation,
    map: map
  });
  google.maps.event.addListener(marker, 'click', function() {
    window.location.href = '<%= @restaurant.url %>';
  });
}
</script>