config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # get 'password_resets/new'
  # get 'password_resets/create'
  # get 'password_resets/edit'
  # get 'password_resets/update'
  resources :password_resets, only: [:new, :create, :edit, :update]
  root 'static_pages#top'
  # root 'restaurants#index'
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resources :restaurants, only: %i[index show] do
    collection do
      get :search
      get :bookmarks
    end
    member do
      post 'update_tag'
    end
  end
  post 'select_restaurants', to: 'restaurants#random_select', as: 'select_restaurants'
  post 'get_location', to: 'locations#get_location'
  resources :bookmarks, only: %i[create destroy]
  get "/pages/*id" => 'pages#show', as: :page, format: false
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
  end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to search_restaurants_path, success: t('.success')
    else
      flash[:error] = t('.fail')
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to login_path, success: t('.success')
  end
end

app/views/user_sessions/new.html.erb
<div class="flex-grow flex items-center justify-center bg-cyan-800">
  <div class="container mx-auto flex justify-center items-center">
    <div class="w-full max-w-xs">
        <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
          <div class="font-bold text-xl mt-4 mb-6 text-center">
            <h1><%= t '.title' %></h1>
          </div>
          <%= form_with model: @user, local: true do |f| %>
            <div class="mb-6">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
            </div>
            <div class="mb-6">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline' %>
            </div>
            <div class="flex justify-center">
              <%= f.submit (t 'defaults.login'), class: 'btn' %>
            </div>
          <% end %>
          <div class='text-center mt-4 px-8'>
            <%= link_to auth_at_provider_path(provider: :google), class: "px-4 py-2 border flex gap-2 border-slate-200 rounded-lg text-slate-700 hover:border-slate-400 hover:text-slate-900 hover:shadow transition duration-150" do %>
              <img class="w-6 h-6" src="https://www.svgrepo.com/show/475656/google-color.svg" loading="lazy" alt="google logo">
              <span>Login with Google</span>
            <% end %>
          </div>
          <div class='text-center mt-4'>
            <%= link_to (t '.to_register_page'), new_user_path %>
          </div>
          <div class='text-center'>
            <%= link_to (t '.password_forget'),new_password_reset_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>